package com.nikolai.education.enums;

public enum UserLogs {
    ACCEPTED_COURSE, DELETE_COURSE, FINISH_TASK, STARTED_COURSE,
    INVITE, CREATE_COURSE,CREAT_TASK, STARTED_TASK, DELETE_USER_FROM_COURSE, DELETE_USER_FROM_ORG
}
