package com.nikolai.education.enums;

public enum UserLogsEnum {
    ACCEPTED_COURSE, DELETE_COURSE, STARTED_COURSE,
    INVITE, CREATE_COURSE,CREAT_TASK, DELETE_USER_FROM_COURSE, DELETE_USER_FROM_ORG, CHANGE_STATUS_TASK,
    DELETE_TASK
}
